eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    registerWithEureka: false
  fetchRegistry: false
  server:
    waitTimeInMisWhenSyncEmpty: 5
    eviction-interval-timer-in-ms: 1000
spring:
  application:
    name: eureka-server